#!/usr/bin/env python3
"""Build a cumulative markdown index of evaluated rxiv papers.

Reads every per-week JSONL file (one paper per line, as produced by the
``gha-rxiv-paper-eval`` workflow's ``extracts.jsonl`` artifact) under
``--data-dir`` and emits a single deduplicated index grouped by the week the
paper was surfaced (newest first). Dedup is by DOI (falling back to title);
when the same paper appears in multiple weeks the newest week wins.

Usage:
    python build-rxiv-index.py \\
        --data-dir triage/rxiv/data \\
        --out triage/rxiv/index.md

Exit codes:
    0 = index written
    2 = fatal error (bad input)
"""

import argparse
import json
import re
import sys
from pathlib import Path

# <server>-<year>-W<week>.jsonl  e.g. arxiv-2026-W22.jsonl
KEY_RE = re.compile(r"(?P<server>.+)-(?P<year>\d{4})-W(?P<week>\d+)\.jsonl$")


def _fatal(message: str) -> None:
    """Print an error to stderr and exit 2 (distinct from a clean run)."""
    print(message, file=sys.stderr)
    sys.exit(2)


def parse_key(filename: str) -> tuple[str, int, int] | None:
    """Parse ``<server>-<year>-W<week>.jsonl`` into (server, year, week)."""
    m = KEY_RE.match(filename)
    if not m:
        return None
    return m.group("server"), int(m.group("year")), int(m.group("week"))


def collect(data_dir: Path) -> tuple[list[dict], int]:
    """Return (deduped records sorted newest-first, number of week files read)."""
    files = sorted(data_dir.glob("*.jsonl"))
    papers: dict[str, dict] = {}  # DOI-or-title -> record
    for f in files:
        key = parse_key(f.name)
        server, year, week = key if key else ("", 0, 0)
        for line in f.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line:
                continue
            try:
                d = json.loads(line)
            except json.JSONDecodeError:
                continue
            doi = (d.get("doi") or "").strip()
            title = (d.get("title") or "(no title)").strip()
            ident = doi or title
            rec = {
                "title": title,
                "doi": doi,
                "extracted": d.get("extracted") or {},
                "server": server,
                "year": year,
                "week": week,
            }
            prev = papers.get(ident)
            if prev is None or (rec["year"], rec["week"]) >= (prev["year"], prev["week"]):
                papers[ident] = rec

    records = sorted(
        papers.values(),
        key=lambda r: (r["year"], r["week"], r["title"].lower()),
        reverse=True,
    )
    return records, len(files)


def render(records: list[dict], week_count: int) -> str:
    """Render the deduped records into a markdownlint-clean index document."""
    lines = [
        "# ArXiv AI-Agent Papers — Cumulative Index",
        "",
        "<!-- Auto-generated by .github/scripts/build-rxiv-index.py from "
        "triage/rxiv/data/*.jsonl. Do not edit by hand. -->",
        "",
        f"{len(records)} unique papers across {week_count} evaluated week(s).",
        "",
    ]
    current_bucket = None
    for r in records:
        bucket = f"{r['year']} W{r['week']:02d} ({r['server']})" if r["year"] else "Unsorted"
        if bucket != current_bucket:
            current_bucket = bucket
            lines += [f"## {bucket}", ""]
        ex = r["extracted"]
        title = r["title"].replace("|", r"\|")
        if r["doi"]:
            # Linked heading ends in ')', so MD026 (trailing punctuation) is safe.
            lines.append(f"### [{title}](https://arxiv.org/abs/{r['doi']})")
        else:
            # Plain heading: strip trailing punctuation to satisfy MD026.
            lines.append(f"### {title.rstrip('.,;:! ')}")
        lines.append("")
        if ex.get("summary"):
            lines.append(f"- summary: {ex['summary']}")
        if ex.get("methods"):
            lines.append(f"- methods: {', '.join(ex['methods'])}")
        if ex.get("key_findings"):
            lines.append(f"- findings: {'; '.join(ex['key_findings'])}")
        lines.append("")

    return "\n".join(lines).rstrip("\n") + "\n"


def main() -> None:
    """Entry point."""
    parser = argparse.ArgumentParser(
        description="Build a cumulative markdown index from rxiv eval JSONL files."
    )
    parser.add_argument("--data-dir", required=True, type=Path)
    parser.add_argument("--out", required=True, type=Path)
    args = parser.parse_args()

    if not args.data_dir.exists():
        _fatal(f"ERROR: data dir does not exist: {args.data_dir}")

    records, week_count = collect(args.data_dir)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render(records, week_count), encoding="utf-8")
    print(f"Wrote {args.out} ({len(records)} papers, {week_count} weeks)", file=sys.stderr)


if __name__ == "__main__":
    main()
